services:
  db:
    image: postgres:15-alpine
    container_name: fastapi-app-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata-${ENVIRONMENT}:/var/lib/postgresql/data

volumes:
  pgdata-dev:
  pgdata-prod:
  pgdata-staging:
